name: helix4d_conda
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py39h06a4308_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h7f8727e_0
  - kiwisolver=1.3.1=py39h2531618_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.0=py39h06a4308_0
  - matplotlib-base=3.5.0=py39h3ed280b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.1=py39hd3c417c_0
  - mkl_random=1.2.2=py39h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pip=21.2.4=py39h06a4308_0
  - pyqt=5.9.2=py39h2531618_6
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py39h27cfd23_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - antlr4-python3-runtime==4.8
    - async-timeout==4.0.2
    - attrs==21.4.0
    - cachetools==5.0.0
    - ccimport==0.3.7
    - charset-normalizer==2.0.10
    - colorlog==6.6.0
    - cumm==0.2.8
    - cumm-cu114==0.2.8
    - decorator==4.4.2
    - fire==0.4.0
    - frozenlist==1.3.0
    - fsspec==2022.1.0
    - future==0.18.2
    - google-auth==2.5.0
    - google-auth-oauthlib==0.4.6
    - googledrivedownloader==0.4
    - grpcio==1.43.0
    - hydra-colorlog==1.1.0
    - hydra-core==1.1.1
    - idna==3.3
    - imageio==2.14.1
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.10.1
    - isodate==0.6.1
    - jinja2==3.0.3
    - joblib==1.1.0
    - lark==1.0.0
    - markdown==3.3.6
    - markupsafe==2.0.1
    - moviepy==1.0.3
    - multidict==6.0.2
    - networkx==2.6.3
    - ninja==1.10.2.3
    - numpy==1.22.1
    - oauthlib==3.1.1
    - omegaconf==2.1.1
    - pandas==1.4.0
    - pccm==0.3.2
    - pillow==9.0.0
    - plotly==5.5.0
    - plyfile==0.7.4
    - portalocker==2.3.2
    - proglog==0.1.9
    - protobuf==3.19.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.9.0
    - pydeprecate==0.3.1
    - pyparsing==3.0.7
    - pytorch-lightning==1.5.9
    - pytz==2021.3
    - pyyaml==6.0
    - rdflib==6.1.1
    - requests==2.27.1
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - setuptools==59.5.0
    - spconv==2.1.21
    - spconv-cu114==2.1.21
    - tenacity==8.0.1
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==1.1.0
    - threadpoolctl==3.0.0
    - torch==1.10.1+cu113
    - torch-geometric==2.0.3
    - torch-scatter==2.0.9
    - torch-sparse==0.6.12
    - torchaudio==0.10.1+cu113
    - torchmetrics==0.7.0
    - torchvision==0.11.2+cu113
    - tqdm==4.62.3
    - typing-extensions==4.0.1
    - urllib3==1.26.8
    - werkzeug==2.0.2
    - yacs==0.1.8
    - yarl==1.7.2
    - zipp==3.7.0